In [52]:
#Array of Zeros and Ones
import numpy as np
print(np.zeros((2,3)))
print(np.ones((3,4)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
import numpy as np
#Creating NumPy Arrays
print(np.array([1,2,3]))     
#2D Array
matrix=np.array([[1,2],[3,4]])
print("2D matrix:")
print(matrix)
#matrix operations
a=np.array([[2,3],[4,5]])
b=np.array([[5,6],[7,8]])
print("Matrix addition:\n",a+b)
print("Matrix multiplication:\n",a*b)
print("Transpose:\n",a.T)
#Diagonal Elements (2D Array)
diag=np.diag(matrix)
print("Diagonal:",diag)

[1 2 3]
2D matrix:
[[1 2]
 [3 4]
 [5 6]]
Matrix addition:
 [[ 7  9]
 [11 13]]
Matrix multiplication:
 [[10 18]
 [28 40]]
Transpose:
 [[2 4]
 [3 5]]
Diagonal: [1 4]


In [68]:
#Array Range and Linespace
import numpy as np
print(np.arange(2,20,3)) 
print(np.arange(5,20))
print(np.linspace(3,30,10))
#reshape operations
a=np.arange(1,10)
print(a.reshape(3,3))


[ 2  5  8 11 14 17]
[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3.  6.  9. 12. 15. 18. 21. 24. 27. 30.]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
import numpy as np 
#Arithmetic operations
a=np.array([10,20,30])
b=np.array([1,2,3])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
#mathemetical functions
print(np.sqrt(25))
print(np.pow(2,5))

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]
5.0
32


In [56]:
import numpy as np
#Statistical Operations
arr=np.array([45,20,50,70,65])
print("Mean",np.mean(arr))
print("Median:",np.median(arr))
print("Sum:",np.sum(arr))
print("Std dev:",np.std(arr))

Mean 50.0
Median: 50.0
Sum: 250
Std dev: 17.60681686165901


In [57]:
#Indexing and Slicing 
import numpy as np 
arr=([10,20,30,40,50,60,70,80,90])
print("Index element:",arr[5])
print(arr[:6])
print(arr[7:])
print(arr[-4])
print(arr[::3])
print(arr[5::])
print(arr[1:7])

Index element: 60
[10, 20, 30, 40, 50, 60]
[80, 90]
60
[10, 40, 70]
[60, 70, 80, 90]
[20, 30, 40, 50, 60, 70]


In [61]:
#multiples
import numpy as np 
arr=np.array([2,3,4,5,6,7,8,9,10,12,14,15])
multiples=arr[arr%3==0]
print("Multiple of 3:",multiples)
multiples=arr[arr%5==0]
print("Multiple of 5:",multiples)
multiples=arr[arr%4!=0]
print("Not a multiple of 4:",multiples)
even=arr[arr%2==0]
print("Even numbers are:",even)
odd=arr[arr%2!=0]
print("Odd numbers are:",odd)

#greater and smaller
greater = arr[arr > 8]
print("Greater numbers are:",greater)
smaller = arr[arr < 8]
print("Smaller numbers are:",smaller)

Multiple of 3: [ 3  6  9 12 15]
Multiple of 5: [ 5 10 15]
Not a multiple of 4: [ 2  3  5  6  7  9 10 14 15]
Even numbers are: [ 2  4  6  8 10 12 14]
Odd numbers are: [ 3  5  7  9 15]
Greater numbers are: [ 9 10 12 14 15]
Smaller numbers are: [2 3 4 5 6 7]
